import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm, ttest_1samp
# Task1
def generate_height_data(size=1000, mean=170, std_dev=10) -> np.ndarray:
    """ Generates dataset of 1000 heights with a mean of 170 cm and standard deviation of 10 cm.

    Args:
        size (int, optional): Defaults to 1000.
        mean (int, optional): Defaults to 170.
        std_dev (int, optional): Defaults to 10.

    Returns:
        np.ndarray: Array of heights
    Rises:
        ValueError: Size must be a positive integer.
        ValueError: Mean height must be a positive number.
        ValueError: Standard deviation must be a positive number.
        ValueError: Standard deviation must be less than the mean.
    """
    if size <= 0 or not isinstance(size, int):
        raise ValueError("Size must be a positive integer.")
    if mean <= 0 or not isinstance(mean, (int, float)):
        raise ValueError("Mean height must be a positive number.")
    if std_dev <= 0 or not isinstance(std_dev, (int, float)):
        raise ValueError("Standard deviation must be a positive number.")
    if std_dev > mean or not isinstance(mean, (int, float)):
        raise ValueError("Standard deviation must be less than the mean.")
    
    # This part of code was generated by ChatGPT for the question: 
    # "Generate a dataset of 1000 heights with a mean of 170 cm and standard deviation of 10 cm."
    return np.random.normal(mean, std_dev, size) 

# Task2
def descriptive_statistics(height_data:np.array) -> tuple:
    """Calculates the mean, median and standard deviation of the height data.

    Args:
        height_data (np.array): 

    Returns:
        tuple: Mean, Median, Standard Deviation
    
    Raises:
        ValueError: Height data must be a numpy array.
        ValueError: Height data cannot be empty.
    
    """
    if not isinstance(height_data, np.ndarray):
        raise ValueError("Height data must be a numpy array.")
    if len(height_data) == 0:
        raise ValueError("Height data cannot be empty.")
    
    mean = np.mean(height_data)
    median = np.median(height_data)
    std_dev = np.std(height_data)
    return (mean, median, std_dev)

# Task3
def visualise_histogram(height_data:np.ndarray):
    """Creates a histogram of the height data.
    """
    if not isinstance(height_data, np.ndarray):
        raise ValueError("Height data must be a numpy array.")
    if len(height_data) == 0:
        raise ValueError("Height data cannot be empty.")
    plt.hist(height_data, bins=30, edgecolor='black', alpha=0.7)
    plt.title('Histogram of Heights')
    plt.xlabel('Height (cm)')
    plt.ylabel('Frequency')
    plt.grid(axis='y', alpha=0.75)
    plt.show()

# Task4
def calculate_percentiles(height_data:np.ndarray) -> tuple:
    """Calculates the 25th, 50th and 75th percentiles of the height data.

    Args:
        height_data (np.ndarray): Array of heights

    Returns:
        float: 25th percentile, 50th percentile, 75th percentile
    Raises:
        ValueError: Height data must be a numpy array.
        ValueError: Height data cannot be empty.
        
    """
    if not isinstance(height_data, np.ndarray):
        raise ValueError("Height data must be a numpy array.")
    if len(height_data) == 0:
        raise ValueError("Height data cannot be empty.")
    p25 = np.percentile(height_data, 25)
    p50 = np.percentile(height_data, 50)
    p75 = np.percentile(height_data, 75)
    return p25, p50, p75

# Task5
def identify_outliers(height_data:np.ndarray) -> np.ndarray:
    """Identifies outliers in the height data using the IQR method.

    Args:
        height_data (np.ndarray): Array of heights

    Returns:
        np.ndarray : Array of outliers
    Raises:
        ValueError: Height data must be a numpy array.
        ValueError: Height data cannot be empty.
    """
    if not isinstance(height_data, np.ndarray):
        raise ValueError("Height data must be a numpy array.")
    if len(height_data) == 0:
        raise ValueError("Height data cannot be empty.")
    
    q1 = np.percentile(height_data, 25)
    q3 = np.percentile(height_data, 75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = height_data[(height_data < lower_bound) | (height_data > upper_bound)]
    return outliers

# Task6
def random_sampling(height_data:np.ndarray) -> np.ndarray:
    """Performs random sampling of 50 heights from the data.

    Args:
        height_data (np.ndarray): Array of heights

    Returns:
        np.ndarray: Random sample of 50 heights
    Raises:
        ValueError: Height data must be a numpy array.
        ValueError: Height data cannot be empty.
    """
    if not isinstance(height_data, np.ndarray):
        raise ValueError("Height data must be a numpy array.")
    if len(height_data) == 0:
        raise ValueError("Height data cannot be empty.")
    sample = np.random.choice(height_data, size=50, replace=False)
    return sample

# Task7
def hypothesis_testing(data:np.ndarray, null_hypothesis_mean=165) -> tuple:
    """Performs a one-sample t-test to test the null hypothesis that the mean height is equal to 165 cm.

    Args:
        data (np.ndarray): Array of heights
        null_hypothesis_mean (int, optional): Mean height for the null hypothesis. Defaults to 165.

    Returns:
        : _description_
    """
    t_stat, p_value = ttest_1samp(data, null_hypothesis_mean)
    if p_value < 0.05:
        print("Reject the null hypothesis: The mean height is significantly different from the hypothesized mean.")
    else:
        print("Fail to reject the null hypothesis: The mean height is not significantly different from the hypothesized mean.")
    return (t_stat, p_value)

def calculate_probability(data:np.ndarray, threshold_height=180) -> np.float64:
    """Calculates the probability of finding a height greater than 180 cm in the dataset.

    Args:
        data (np.ndarray): Array of heights
        threshold_height (int, optional): . Defaults to 180.

    Returns:
        np.float64: 
    """
    mean = np.mean(data)
    std_dev = np.std(data)
    probability = 1 - norm.cdf(threshold_height, loc=mean, scale=std_dev)
    return probability

# Example Usage
if __name__ == "__main__":
    heights = generate_height_data()
    t_stat, p_value = hypothesis_testing(heights)
    print("t-statistic:", t_stat)
    print("p-value:", p_value)
    
    # descriptive_statistics(heights)
    # visualise_histogram(heights)
    # calculate_percentiles(heights)
    # identify_outliers(heights)
    # random_sampling(heights)
    # hypothesis_testing(heights)
    # calculate_probability(heights)
