import argparse
import re
from  a import shingles


def preprocess_text(text: str, remove_punctuation: bool) -> str:
    """
    preprocessing the text by optionally removing punctuation.

    args:
        text (str): input text.
        remove_punctuation (bool): whether to remove punctuation.

    returns:
        str: processed text.
    """
    if remove_punctuation:
        text = re.sub(r'[^\w\s]', '', text) # the code was generated by ChatGPT with the prompt:
        # "modify the code to remove punctuation" the code uses regex to remove punctuation
    return text


def jaccard_similarity(set1, set2):
    """
    calculateing the jaccard similarity between two sets.

    args:
        set1 (set): first set.
        set2 (set): second set.

    returns:
        float: jaccard similarity (intersection / union).
    """
    intersection = set1 & set2
    union = set1 | set2
    return len(intersection) / len(union)


def compare_files(file1: str, file2: str, k: int, remove_punctuation: bool) -> float:
    """
    comparing two files by calculating the jaccard similarity of their kshingles

    args:
        file1 (str): path to the first file.
        file2 (str): path to the second file.
        k (int): size of shingles (k-grams).
        remove_punctuation (bool): whether to remove punctuation.

    returns:
        float: jaccard similarity
    """
    with open(file1, 'r') as f1, open(file2, 'r') as f2:
        text1 = preprocess_text(f1.read(), remove_punctuation)
        text2 = preprocess_text(f2.read(), remove_punctuation)

    shingles1 = set(shingles(text1.split(), k))
    shingles2 = set(shingles(text2.split(), k))
    return jaccard_similarity(shingles1, shingles2)


def main():
    parser = argparse.ArgumentParser(description="compare two text files using jaccard similarity.")
    parser.add_argument("--query", type=str, required=True, help="path to the query text file.")
    parser.add_argument("--target", type=str, required=True, help="path to the target text file.")
    parser.add_argument("-k", type=int, required=True, help="size of the shingles (k-grams).")
    parser.add_argument("--remove_punctuation", action="store_true", help="remove punctuation from text.")
    args = parser.parse_args()

    similarity = compare_files(args.query, args.target, args.k, args.remove_punctuation)
    print(f"jaccard similarity: {similarity:.4f}")


if __name__ == "_main_":
    main()